version: '2'
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db/
  heyburrito:
    build: .
    image: theo-flatten-ios/heyburrito
    ports:
      - "3333:3333"
      #- "8080:8080"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
    links:
      - mongodb
